Data Encoding হলো এমন একটি প্রক্রিয়া যার মাধ্যমে ক্যাটাগরিক্যাল ডেটা (Categorical Data) বা টেক্সট ডেটাকে সংখ্যায় (Numerical values) রূপান্তর করা হয়।মেশিন লার্নিং মডেলগুলো মূলত গাণিতিক সমীকরণের ওপর ভিত্তি করে কাজ করে, তাই তারা সরাসরি "Male/Female" বা "Red/Blue" এর মতো টেক্সট বুঝতে পারে না। মডেলকে ডেটা বোঝানোর জন্য এনকোডিং অপরিহার্য।Data Encoding-এর প্রধান প্রকারভেদপ্রধানত দুই ধরনের এনকোডিং সবচেয়ে বেশি ব্যবহৃত হয়:১. Label Encoding (অর্ডিনাল ডেটার জন্য)যখন ডেটার মধ্যে একটি নির্দিষ্ট ক্রম বা সিরিয়াল (Order) থাকে, তখন এটি ব্যবহার করা হয়। এটি প্রতিটি ক্যাটাগরিকে একটি নির্দিষ্ট নম্বর (০, ১, ২...) দেয়।উদাহরণ: শিক্ষাগত যোগ্যতা (SSC, HSC, BSc)।SSC $\rightarrow$ 0HSC $\rightarrow$ 1BSc $\rightarrow$ 2কখন ব্যবহার করবেন: যখন Rank বা গুরুত্বের ব্যাপার থাকে।২. One-Hot Encoding (নমিনাল ডেটার জন্য)যখন ডেটার মধ্যে কোনো সিরিয়াল বা ক্রম থাকে না, তখন এটি ব্যবহার করা হয়। এটি প্রতিটি ইউনিক ক্যাটাগরির জন্য আলাদা আলাদা নতুন কলাম তৈরি করে এবং সেখানে ০ বা ১ বসায়।উদাহরণ: শহরের নাম (Dhaka, Khulna, Sylhet)।এখানে কেউ কারো চেয়ে বড় বা ছোট নয়।এটি 'Dhaka' এর জন্য একটি কলাম তৈরি করবে যেখানে ঢাকা থাকলে ১ হবে, অন্যথায় ০।
Nominal Data: যেখানে কোনো ক্রম নেই (যেমন: লিঙ্গ, রঙ) One-Hot Encoding ব্যবহার করুন।Ordinal Data: যেখানে ক্রম আছে (যেমন: ভালো, খুব ভালো, চমৎকার) Label Encoding ব্যবহার করুন।

## Nominal/OHE encoding
**One-Hot Encoding**-এর প্রধান সমস্যাগুলো সংক্ষেপে নিচে দেওয়া হলো:

1.  **High Dimensionality:** ক্যাটাগরির সংখ্যা বেশি হলে কলামের সংখ্যাও অনেক বেড়ে যায়। যেমন, ১০০০টি শহরের নামের জন্য ১০০০টি নতুন কলাম তৈরি হবে।
2.  **Sparsity:** নতুন কলামগুলোর অধিকাংশ জায়গা **০ (Zero)** দিয়ে পূর্ণ থাকে, যা মেমরি (RAM) অপচয় করে।
3.  **Dummy Variable Trap:** ভেরিয়েবলগুলোর মধ্যে নিজেদের মধ্যে সম্পর্ক তৈরি হয়, যা লিনিয়ার রিগ্রেশনের মতো মডেলের নির্ভুলতা কমিয়ে দেয়।
4.  **Training Time:** ডেটা বড় হয়ে যাওয়ায় মডেল ট্রেনিং করতে অনেক বেশি সময় লাগে।
5.  **Loss of Order:** ক্যাটাগরির মধ্যে কোনো ক্রম (যেমন: Good > Bad) থাকলে সেই তথ্যটি হারিয়ে যায়।



**সমাধান:** ক্যাটাগরি খুব বেশি হলে **Binary Encoding** বা **Target Encoding** ব্যবহার করা ভালো।

In [33]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [34]:
## Create a simple dataframe
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [35]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [36]:
## craete an instance of oHE
encoder = OneHotEncoder()

## PErform fit and transform
encoded= encoder.fit_transform(df[['color']]).toarray()

In [37]:
import pandas as pd
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [38]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [39]:
## For new data
encoder.transform([['blue']]).toarray()

c:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [40]:
pd.concat([df,encoder_df],axis =1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [41]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [42]:
## Label encoder
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [44]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [46]:
## For new value
lbl_encoder.transform([['red']])

c:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [47]:
lbl_encoder.transform([['blue']])

c:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [48]:
lbl_encoder.transform([['green']])

c:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

ORdinal encoding

এনকোডিং এর ধরন,কখন ব্যবহার করবেন?,উদাহরণ
Ordinal Encoding,যখন ডেটার মধ্যে একটি Order বা ক্রম থাকে।,"সন্তুষ্টির মাত্রা (Satisfied, Neutral, Dissatisfied)"
Label Encoding,সাধারণত Target Variable (আউটপুট কলাম) এনকোড করতে এটি ব্যবহার করা হয়।,"ইমেইল ক্যাটাগরি (Spam, Not Spam)"

In [49]:
## Ordinal encoding respect to the ranking
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
    'size': ['small','medium','large','small','medium','large']
})

In [50]:
df

     size
0   small
1  medium
2   large
3   small
4  medium
5   large

In [51]:
## Asigned rankings
## create an instance of OrdinalEncoder and then fit_transform
encoder= OrdinalEncoder(categories=[['small','medium','large']])

In [53]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.]])

In [54]:
encoder.transform([['small']])

c:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

Target guided ordinal encoding

In [56]:
import pandas as pd
## create a simple datafrmae with a categorical variable and target variable
df = pd.DataFrame({
    'city':['new york','london','paris','tokyo','new york','paris'],
    'price':[200,150,300,250,180,320]
})
df

       city  price
0  new york    200
1    london    150
2     paris    300
3     tokyo    250
4  new york    180
5     paris    320

In [57]:
df.groupby('city')['price'].mean()

city
london      150.0
new york    190.0
paris       310.0
tokyo       250.0
Name: price, dtype: float64

In [58]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [59]:
mean_price

{'london': 150.0, 'new york': 190.0, 'paris': 310.0, 'tokyo': 250.0}

In [61]:
df['city_encoded'] = df['city'].map(mean_price)
df[['city', 'price', 'city_encoded']]

       city  price  city_encoded
0  new york    200         190.0
1    london    150         150.0
2     paris    300         310.0
3     tokyo    250         250.0
4  new york    180         190.0
5     paris    320         310.0

In [62]:
df[['price', 'city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [ ]:
import seaborn as sns

import matplotlib.pyplot as plt

# Load the tips dataset
tips = sns.load_dataset('tips')

# Compare bills with sex using a boxplot
sns.boxplot(data=tips, x='sex', y='total_bill')
plt.title('Bill Comparison by Sex')
plt.show()